import {
  Activity,
  AlertCircle,
  AlertOctagon,
  AlertTriangle,
  AlignCenter,
  AlignJustify,
  AlignLeft,
  AlignRight,
  Anchor,
  Aperture,
  Archive,
  ArrowDown,
  ArrowDownCircle,
  ArrowDownLeft,
  ArrowDownRight,
  ArrowLeft,
  ArrowLeftCircle,
  ArrowLeftRight,
  ArrowRight,
  ArrowRightCircle,
  ArrowUp,
  ArrowUpCircle,
  ArrowUpDown,
  ArrowUpLeft,
  ArrowUpRight,
  AtSign,
  Award,
  BarChart,
  BarChart2,
  Battery,
  BatteryCharging,
  Bell,
  BellOff,
  Bluetooth,
  Bold,
  Book,
  Bookmark,
  BookOpen,
  Box,
  Briefcase,
  Calculator,
  Calendar,
  CalendarClock,
  Camera,
  CameraOff,
  Cast,
  Check,
  CheckCircle,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsDown,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUp,
  ChevronUp,
  Chrome,
  Circle,
  Clipboard,
  Clock,
  Code,
  Codepen,
  Codesandbox,
  Coffee,
  Columns,
  Command,
  Compass,
  Copy,
  CornerDownLeft,
  CornerDownRight,
  CornerLeftDown,
  CornerLeftUp,
  CornerRightDown,
  CornerRightUp,
  CornerUpLeft,
  CornerUpRight,
  Cpu,
  CreditCard,
  Crop,
  Crosshair,
  Database,
  Delete,
  Diamond,
  Disc,
  DollarSign,
  Download,
  Droplet,
  Edit,
  Edit2,
  Edit3,
  ExternalLink,
  Eye,
  EyeOff,
  FastForward,
  Feather,
  Figma,
  File,
  FileCode,
  FileDigit,
  FileMinus,
  FilePlus,
  FileText,
  FileVideo,
  Film,
  Filter,
  Flag,
  Flame,
  Folder,
  FolderMinus,
  FolderOpen,
  FolderPlus,
  Framer,
  Frown,
  FunctionSquare,
  Gauge,
  Gavel,
  Gift,
  GitBranch,
  GitCommit,
  GitFork,
  Github,
  GitMerge,
  GitPullRequest,
  Globe,
  Grid,
  HardDrive,
  Hash,
  Headphones,
  Heart,
  HelpCircle,
  Hexagon,
  Home,
  Hourglass,
  Image,
  Inbox,
  Info,
  Italic,
  Key,
  Laptop,
  Layers,
  Layout,
  LifeBuoy,
  Link,
  Link2,
  List,
  Loader,
  Lock,
  LogIn,
  LogOut,
  LucideIcon,
  Mail,
  Map,
  MapPin,
  Maximize,
  Maximize2,
  Meh,
  Menu,
  MessageCircle,
  MessageSquare,
  Mic,
  MicOff,
  Minimize,
  Minimize2,
  Minus,
  MinusCircle,
  MinusSquare,
  Monitor,
  Moon,
  MoreHorizontal,
  MoreVertical,
  MousePointer,
  Move,
  Music,
  Navigation,
  Navigation2,
  Octagon,
  Package,
  PackagePlus,
  Paperclip,
  Pause,
  PauseCircle,
  PenTool,
  Percent,
  Phone,
  PhoneCall,
  PhoneForwarded,
  PhoneIncoming,
  PhoneMissed,
  PhoneOff,
  PhoneOutgoing,
  PieChart,
  Play,
  PlayCircle,
  Plus,
  PlusCircle,
  PlusSquare,
  Pocket,
  Power,
  Printer,
  Puzzle,
  Radio,
  RefreshCcw,
  RefreshCw,
  Repeat,
  Rewind,
  RotateCcw,
  RotateCw,
  Rss,
  Save,
  Scissors,
  Search,
  Send,
  Server,
  Settings,
  Share,
  Share2,
  Shield,
  ShieldOff,
  ShoppingBag,
  ShoppingCart,
  Shuffle,
  Sidebar,
  SkipBack,
  SkipForward,
  Slack,
  Slash,
  Sliders,
  Smartphone,
  Smile,
  Speaker,
  Split,
  Square,
  Star,
  StarOff,
  StopCircle,
  Sun,
  Sunrise,
  Sunset,
  Tablet,
  Tag,
  Target,
  Terminal,
  Thermometer,
  ThumbsDown,
  ThumbsUp,
  Timer,
  TimerOff,
  ToggleLeft,
  ToggleRight,
  Trash,
  Trash2,
  Trello,
  TrendingDown,
  TrendingUp,
  Triangle,
  Truck,
  Tv,
  Twitter,
  Type,
  Umbrella,
  Underline,
  Unlock,
  Upload,
  User,
  UserCheck,
  UserMinus,
  UserPlus,
  Users,
  UserX,
  Video,
  VideoOff,
  Voicemail,
  Volume,
  Volume1,
  Volume2,
  VolumeX,
  Wallet,
  Watch,
  Wifi,
  WifiOff,
  Wind,
  Wrench,
  X,
  XCircle,
  XOctagon,
  XSquare,
  Youtube,
  Zap,
  ZapOff,
  ZoomIn,
  ZoomOut,
  ArrowDownRightFromCircle,
  Network,
  FileCog,
  UserCog,
  HeartHandshake,
  MonitorPlay,
  Coins,
  UserCircle,
  ArrowUpRightFromCircle,
  Fan,
} from 'lucide-react';
import {
  Alerting,
  Apple,
  Bug,
  Bug1,
  Deployment,
  Discord,
  Ethereum,
  Google,
  Linux,
  Organization,
  Project,
  ProxyContract,
  Sentry,
  SingleProject,
  Slack1,
  SupportCall,
  Telegram,
  Windows,
} from './icons';
import { IconType } from './Icon.types';

const iconsMap: { [key in IconType]: LucideIcon | any } = {
  'arrow-up-right-from-circle': ArrowUpRightFromCircle,
  'arrow-down-right-from-circle': ArrowDownRightFromCircle,
  fan: Fan,
  network: Network,
  'file-cog': FileCog,
  bug: Bug,
  bug1: Bug1,
  sentry: Sentry,
  timer: Timer,
  'timer-off': TimerOff,
  ethereum: Ethereum,
  linux: Linux,
  apple: Apple,
  windows: Windows,
  deployment: Deployment,
  diamond: Diamond,
  project: Project,
  organization: Organization,
  alerting: Alerting,
  'single-project': SingleProject,
  telegram: Telegram,
  discord: Discord,
  github: Github,
  google: Google,
  slack: Slack,
  activity: Activity,
  'alert-circle': AlertCircle,
  'alert-octagon': AlertOctagon,
  'alert-triangle': AlertTriangle,
  'align-center': AlignCenter,
  'align-justify': AlignJustify,
  'align-left': AlignLeft,
  'align-right': AlignRight,
  anchor: Anchor,
  aperture: Aperture,
  archive: Archive,
  'arrow-down': ArrowDown,
  'arrow-down-circle': ArrowDownCircle,
  'arrow-down-left': ArrowDownLeft,
  'arrow-down-right': ArrowDownRight,
  'arrow-left': ArrowLeft,
  'arrow-left-circle': ArrowLeftCircle,
  'arrow-left-right': ArrowLeftRight,
  'arrow-right': ArrowRight,
  'arrow-right-circle': ArrowRightCircle,
  'arrow-up': ArrowUp,
  'arrow-up-circle': ArrowUpCircle,
  'arrow-up-left': ArrowUpLeft,
  'arrow-up-right': ArrowUpRight,
  'arrow-up-down': ArrowUpDown,
  'at-sign': AtSign,
  award: Award,
  wallet: Wallet,
  'bar-chart': BarChart,
  'bar-chart-2': BarChart2,
  battery: Battery,
  'battery-charging': BatteryCharging,
  bell: Bell,
  'bell-off': BellOff,
  bluetooth: Bluetooth,
  bold: Bold,
  book: Book,
  'book-open': BookOpen,
  bookmark: Bookmark,
  box: Box,
  briefcase: Briefcase,
  calendar: Calendar,
  'calendar-clock': CalendarClock,
  calculator: Calculator,
  camera: Camera,
  'camera-off': CameraOff,
  cast: Cast,
  check: Check,
  'check-circle': CheckCircle,
  'check-square': CheckSquare,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'chevrons-down': ChevronsDown,
  'chevrons-left': ChevronsLeft,
  'chevrons-right': ChevronsRight,
  'chevrons-up': ChevronsUp,
  chrome: Chrome,
  circle: Circle,
  clipboard: Clipboard,
  clock: Clock,
  code: Code,
  codepen: Codepen,
  codesandbox: Codesandbox,
  coffee: Coffee,
  coins: Coins,
  columns: Columns,
  command: Command,
  compass: Compass,
  copy: Copy,
  'corner-down-left': CornerDownLeft,
  'corner-down-right': CornerDownRight,
  'corner-left-down': CornerLeftDown,
  'corner-left-up': CornerLeftUp,
  'corner-right-down': CornerRightDown,
  'corner-right-up': CornerRightUp,
  'corner-up-left': CornerUpLeft,
  'corner-up-right': CornerUpRight,
  cpu: Cpu,
  'credit-card': CreditCard,
  crop: Crop,
  crosshair: Crosshair,
  database: Database,
  delete: Delete,
  disc: Disc,
  'dollar-sign': DollarSign,
  download: Download,
  droplet: Droplet,
  edit: Edit,
  'edit-2': Edit2,
  'edit-3': Edit3,
  'external-link': ExternalLink,
  eye: Eye,
  'heart-handshake': HeartHandshake,
  'monitor-play': MonitorPlay,
  'eye-off': EyeOff,
  'fast-forward': FastForward,
  feather: Feather,
  figma: Figma,
  file: File,
  'file-code': FileCode,
  'file-digit': FileDigit,
  'file-minus': FileMinus,
  'file-plus': FilePlus,
  'file-text': FileText,
  'file-video': FileVideo,
  film: Film,
  filter: Filter,
  flame: Flame,
  flag: Flag,
  folder: Folder,
  'folder-minus': FolderMinus,
  'folder-open': FolderOpen,
  'folder-plus': FolderPlus,
  framer: Framer,
  frown: Frown,
  'function-square': FunctionSquare,
  gavel: Gavel,
  gauge: Gauge,
  gift: Gift,
  'git-branch': GitBranch,
  'git-commit': GitCommit,
  'git-merge': GitMerge,
  'git-pull-request': GitPullRequest,
  globe: Globe,
  grid: Grid,
  'hard-drive': HardDrive,
  hash: Hash,
  headphones: Headphones,
  heart: Heart,
  'help-circle': HelpCircle,
  hexagon: Hexagon,
  home: Home,
  image: Image,
  inbox: Inbox,
  info: Info,
  italic: Italic,
  key: Key,
  layers: Layers,
  layout: Layout,
  'life-buoy': LifeBuoy,
  link: Link,
  'link-2': Link2,
  list: List,
  loader: Loader,
  lock: Lock,
  'log-in': LogIn,
  'log-out': LogOut,
  mail: Mail,
  map: Map,
  'map-pin': MapPin,
  maximize: Maximize,
  'maximize-2': Maximize2,
  meh: Meh,
  menu: Menu,
  'message-circle': MessageCircle,
  'message-square': MessageSquare,
  mic: Mic,
  'mic-off': MicOff,
  minimize: Minimize,
  'minimize-2': Minimize2,
  minus: Minus,
  'minus-circle': MinusCircle,
  'minus-square': MinusSquare,
  monitor: Monitor,
  moon: Moon,
  'more-horizontal': MoreHorizontal,
  'more-vertical': MoreVertical,
  'mouse-pointer': MousePointer,
  move: Move,
  music: Music,
  navigation: Navigation,
  'navigation-2': Navigation2,
  octagon: Octagon,
  package: Package,
  'package-plus': PackagePlus,
  paperclip: Paperclip,
  pause: Pause,
  'pause-circle': PauseCircle,
  'pen-tool': PenTool,
  percent: Percent,
  phone: Phone,
  'phone-call': PhoneCall,
  'phone-forwarded': PhoneForwarded,
  'phone-incoming': PhoneIncoming,
  'phone-missed': PhoneMissed,
  'phone-off': PhoneOff,
  'phone-outgoing': PhoneOutgoing,
  'pie-chart': PieChart,
  play: Play,
  'play-circle': PlayCircle,
  plus: Plus,
  'plus-circle': PlusCircle,
  'plus-square': PlusSquare,
  puzzle: Puzzle,
  pocket: Pocket,
  power: Power,
  printer: Printer,
  radio: Radio,
  'refresh-ccw': RefreshCcw,
  'refresh-cw': RefreshCw,
  repeat: Repeat,
  rewind: Rewind,
  'rotate-ccw': RotateCcw,
  'rotate-cw': RotateCw,
  rss: Rss,
  save: Save,
  scissors: Scissors,
  search: Search,
  send: Send,
  server: Server,
  settings: Settings,
  share: Share,
  'share-2': Share2,
  shield: Shield,
  'shield-off': ShieldOff,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  shuffle: Shuffle,
  sidebar: Sidebar,
  'skip-back': SkipBack,
  'skip-forward': SkipForward,
  slack1: Slack1,
  slash: Slash,
  sliders: Sliders,
  smartphone: Smartphone,
  smile: Smile,
  speaker: Speaker,
  split: Split,
  square: Square,
  star: Star,
  'star-off': StarOff,
  'stop-circle': StopCircle,
  sun: Sun,
  sunrise: Sunrise,
  sunset: Sunset,
  tablet: Tablet,
  tag: Tag,
  target: Target,
  terminal: Terminal,
  thermometer: Thermometer,
  'thumbs-down': ThumbsDown,
  'thumbs-up': ThumbsUp,
  'toggle-left': ToggleLeft,
  'toggle-right': ToggleRight,
  trash: Trash,
  'trash-2': Trash2,
  trello: Trello,
  'trending-down': TrendingDown,
  'trending-up': TrendingUp,
  triangle: Triangle,
  truck: Truck,
  tv: Tv,
  type: Type,
  umbrella: Umbrella,
  underline: Underline,
  unlock: Unlock,
  upload: Upload,
  user: User,
  'user-check': UserCheck,
  'user-minus': UserMinus,
  'user-plus': UserPlus,
  'user-x': UserX,
  users: Users,
  video: Video,
  'video-off': VideoOff,
  voicemail: Voicemail,
  volume: Volume,
  'volume-1': Volume1,
  'volume-2': Volume2,
  'volume-x': VolumeX,
  watch: Watch,
  wifi: Wifi,
  'wifi-off': WifiOff,
  wind: Wind,
  wrench: Wrench,
  x: X,
  'x-circle': XCircle,
  'x-octagon': XOctagon,
  'x-square': XSquare,
  youtube: Youtube,
  zap: Zap,
  'zap-off': ZapOff,
  'zoom-in': ZoomIn,
  'zoom-out': ZoomOut,
  'support-call': SupportCall,
  twitter: Twitter,
  'proxy-contract': ProxyContract,
  hourglass: Hourglass,
  laptop: Laptop,
  'git-fork': GitFork,
  'user-cog': UserCog,
  'user-circle': UserCircle,
};

export { iconsMap };
